### ISSUE TITLE
🦋 Onboarding issue checklist

### ISSUE THREAD

**Issue by jasdumas** [dalyanalytics/admiral#1]
Purpose: Get familiar to `admiral` contribution strategy in preparation for [`admiralpeds`](https://github.com/pharmaverse/admiralpeds)

Reference: https://github.com/pharmaverse/admiral/issues/1839

- [x] Get write access to `admiral`
- [x] Fork `admiral`
- [x] update RStudio
- [x] install [xcode](https://forums.developer.apple.com/forums/thread/673827) to enable Rstudio <> Github repos
- [ ] Watch the onboarding [youtube video](https://www.youtube.com/watch?v=YcDxBmlpykw)
- [x] Read the `admiraldev` [programming strategy guide](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html)
...more to come
